# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171010_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='ID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
