# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171010_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
