# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_block_my'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='my',
            field=models.ManyToManyField(blank=True, to='core.Block'),
        ),
    ]
