# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171101_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Time'),
            preserve_default=False,
        ),
    ]
